services:
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      # ON UTILISE LES VOLUMES NOMMÉS GÉRÉS PAR DOKPLOY
      - rag_storage_volume:/app/data/rag_storage
      - rag_inputs_volume:/app/data/inputs
      - /app/config.ini:/app/config.ini
      - /app/.env:/app/.env
    env_file:
      - .env
    environment:
      - WORKING_DIR=/app/data/rag_storage
      - INPUT_DIR=/app/data/inputs
      - WORKSPACE=default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    extra_hosts:
      - "host.docker.internal:host-gateway"

# C'EST ICI QUE TOUT SE JOUE POUR DOKPLOY
volumes:
  rag_storage_volume:
    name: rag-lightrag-storage-data
  rag_inputs_volume:
    name: rag-lightrag-inputs-data
